routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', function () {
    return redirect(route('products.index'));
});


Route::get('/home', 'ProductController@index');

// Route::get('/cart', function() {
// 	return view('cart');
// })->name('cart');

Route::post('transaction/paypal/create', 'TransactionController@paypal_store');

Route::delete('/carts/clear', 'CartController@clearCart')->name('carts.clear');

Route::resource('products', 'ProductController');

Route::resource('categories', 'CategoryController');

Route::resource('carts', 'CartController');

Route::resource('transactions', 'TransactionController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use App\Product;
use App\Status;

use Illuminate\Http\Request;
use Session;
use Auth;
Use Str;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        

        if (Auth::user()->role_id === 2) {
            $statuses = Status::all();
            $user_id = Auth::user()->id;
            $transactions = Transaction::where('user_id', $user_id)->orderBy('created_at', 'DESC')->get();

            //  $transaction = Transaction::where('payment_modes', $user_id);
             // $transaction = Transaction::where('column from Transation', value to be searched);
            // dd($transactions);
            return view('transactions.index')
                ->with('my_transactions', $transactions)
                ->with('statuses', $statuses);
        }
        
        if (Auth::user()->role_id === 1) {
            $statuses = Status::all();
            $transactions = Transaction::orderBy('created_at', 'DESC')->get();

            //  $transaction = Transaction::where('payment_modes', $user_id);
             // $transaction = Transaction::where('column from Transation', value to be searched);
            // dd($transactions);
            return view('transactions.index')
                ->with('my_transactions', $transactions)
                ->with('statuses', $statuses);
        }

        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Transaction $transaction)
    {
        // Flow
        // 1. Create an entry in Transactions table with the following attributes
        //      transaction number
        //      user_id
        //      payment_mode
        //      status
        // 2. add entries to transaction_orders linked to the newly created entry in the transactions table.
        //      quantity
        //      price
        //      subtotal
        //      product_id
        //      transaction_id
        // 3. compute the total of price
        // 4. update the total attribute of the newly created entry in transaction
        // 5. clear cart session.

        // pre-requisite make seeder for the ff

        // statuses table:
        // pending
        // completed

        // payment_modes table:
        // cash on delivery
        // paypal


        // 1.
        // create transaction code
        $this->authorize('create', $transaction);

        $transaction = new Transaction;

        // userid+random+time()
        $transaction_number = Auth::user()->id . "_" . Str::random(10) . "_" . time();
        // dd($transaction_number);
        
        $user_id = Auth::user()->id;
        // dd($user_id);

        $transaction->transaction_number = $transaction_number;
        $transaction->user_id = $user_id;
        $transaction->save();

        // dd(Session::all());
        // dd(Session::get('cart'));

        // 2. add entries to transaction_orders linked to the newly created entry in the transactions table.
        //  2.1 get the keys from the session; this contains the products and quantity of the user wants to buy
        //  2.2 use the array of product id to find it in the database
        //  2.3 for every product listed in cart, add entry to the pivot table(transaction_product).
        //      quantity
        //      price
        //      subtotal
        //      product_id
        //      transaction_id

        $cart_ids = array_keys(Session::get('cart'));

        $products = Product::find($cart_ids);


        // dd(Session::all());
        
        // $transaction->products()->attach(id of referenced table--product)
        
        // this wont work because we dont have belongToMany @ Product Controller
        // $product->transactions()->attach(id of transaction)

        // $transaction->products()->attach(2)


        foreach (Session::get('cart') as $cart_order_id => $quantity) {
            foreach ($products as $product) {
                if ($product->id == $cart_order_id) {
                    $transaction->products()->attach( 
                        $product->id,
                        [
                            'quantity' => $quantity,
                            'price' => $product->price,
                            'subtotal' => $quantity * $product->price
                        ]
                    );
                }   
            }
        }

        $total = 0;
        // 3. compute the total of price
        $transaction_products = $transaction->products;
        foreach ($transaction_products as $product) {
            # code...
            $total += $product->pivot->subtotal;
        }

        // dd($total);

        // 4. update the total attribute of the newly created entry in transaction

        $transaction->total = $total;
        $transaction->save();

        // 5. clear cart session.

        Session::forget("cart");

        return redirect(route('transactions.show', ['transaction' => $transaction->id ]))->with('Checkout_success', 'Your order has been processed.');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        $this->authorize('view', $transaction);
        return view('transactions.show', ['transaction'=>$transaction]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        $this->authorize('update', $transaction);

        $transaction->status_id = $request->input('status');
        $transaction->save();

        // redirect with() will be read as a session
        return redirect(route('transactions.index'))->with('transaction_updated', $transaction->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }


    public function paypal_store(Request $request)
    {
        $data = json_decode($request->getContent(), true);

        $transaction = new Transaction;


        $transaction_number = $data['transactionNumber'];
        $user_id = Auth::user()->id;

        $transaction->transaction_number = $transaction_number;
        $transaction->user_id = $user_id;
        $transaction->payment_mode_id = 2;
        $transaction->save();

        $cart_ids = array_keys(Session::get('cart'));

        $products = Product::find($cart_ids);

        foreach (Session::get('cart') as $cart_order_id => $quantity) {
            foreach ($products as $product) {
                if ($product->id == $cart_order_id) {
                    $transaction->products()->attach( 
                        $product->id,
                        [
                            'quantity' => $quantity,
                            'price' => $product->price,
                            'subtotal' => $quantity * $product->price
                        ]
                    );
                }   
            }
        }

        $total = 0;
        $transaction_products = $transaction->products;
        foreach ($transaction_products as $product) {
            $total += $product->pivot->subtotal;
        }

        $transaction->total = $total;
        $transaction->save();

        Session::forget("cart");

        return ["url" => route('transactions.show', ['transaction' => $transaction->id ]) ];
    }

}

resources/views/transactions/index.blade.php
@extends('layouts.app')


@section('content')



<div class="container-fluid">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">

			<h2 class="text-center">Transactions</h2>

			<div class="accordion" id="transactionAccordion">

				{{-- {{ dd(Session::all()) }} --}}

				@foreach ($my_transactions as $transaction)
				<div class="card shadow bg-white rounded">
					<div class="card-header" id="headingOne">
						<h2 class="mb-0">
							<button 
								class="btn btn-block text-left" 
								type="button" 
								data-toggle="collapse" 
								data-target="#transaction-{{$transaction->id }}" 
								aria-expanded="false" 
								aria-controls="collapseOne">
								{{$transaction->transaction_number }} / {{ $transaction->created_at->format('F d, Y - h:i') }}  
								@if (Session::has('transaction_updated') && Session::get('transaction_updated') == $transaction->id )
									<span class="badge badge-info"> Status Updated </span>
								@endif

								@if ($transaction->status->name == "Pending")
									<span class="badge badge-warning float-right">{{$transaction->status->name }}</span>

								@else
									<span class="badge badge-success float-right">{{$transaction->status->name }}</span>

								@endif
								
							</button>

						</h2>
					</div>

					<div id="transaction-{{$transaction->id }}" class="collapse" aria-labelledby="headingOne" data-parent="#transactionAccordion">
						<div class="card-body">
							<h5 class="card-title text-center">Summary</h5>
							<div class="table-responsive mb-3">

								<table class="table table-sm table-borderless">
									<tbody>
										<tr>
											<td>Customer Name:</td>
											<td><strong>{{$transaction->user->name }}</strong></td>
										</tr>
										<tr>
											<td>Transaction Number:</td>
											<td><strong>{{ $transaction->transaction_number }}</strong></td>
										</tr>
										<tr>
											<td>Mode of Payment:</td>
											<td>{{ $transaction->payment_mode->name }}</td>
										</tr>
										<tr>
											<td>Status</td>
											<td>{{ $transaction->status->name }}

												@can('isAdmin')
												<form action="{{ route('transactions.update', ['transaction'=> $transaction->id]) }} " method="POST" class="p-3 bg-secondary rounded">
													@csrf
													@method('PUT')

													<label for="edit-transaction-{{$transaction->id}}">Change Status</label>
													<button class="btn btn-primary mb-1 float-right ">Change Status</button>
													<span>
														<select class="custom-select mb-1" id="edit-transaction-{{$transaction->id}}" name="status">
															@foreach($statuses as $status)

																<option value="{{ $status->id}} " 
																	@if ($transaction->status_id == $status->id)
																		selected
																	@endif
																> {{$status->name }} </option>

															@endforeach
														</select>
													</span>
												</form>
												@endcan
											</td>
										</tr>
										<tr>
											<td>Date</td>
											<td>{{$transaction->created_at->format('F d, Y')}}</td>
										</tr>
										<tr>
											<td>Total</td>
											<td> &#8369; {{ number_format($transaction->total, 2) }} </td>
										</tr>
									</tbody>
									<tfoot>
										<tr>
											<td colspan="2">
												<a href=" {{ route('transactions.show', ['transaction'=>$transaction->id]) }} " class="page-link text-center rounded">View Details</a>
											</td>
										</tr>
									</tfoot>
								</table>

							</div>
						</div>
					</div>
				</div>

				@endforeach

		</div>
	</div>
</div>




@endsection

resources/views/transactions/show.blade.php
@extends('layouts.app')

@section('content')
	{{-- {{$transaction->user->name}} --}}



{{-- 	@foreach ($transaction->products as $transaction_product)
		{{ $transaction_product->name }}


	@endforeach --}}

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 mx-auto">
				<h3 class="text-center">Transaction Details</h3>
				<hr>
			</div>
			{{-- end of col --}}
		</div>
		{{-- end of row --}}


		<div class="row">
			<div class="col-12 col-md-12 mx-auto">

				<div class="table-responsive">
					<table class="table table-sm table-borderless">

						<tbody>
							<tr>
								<td>Customer Name:</td>
								<td><strong>{{$transaction->user->name}}</strong></td>
							</tr>
							<tr>
								<td>Transaction Number:</td>
								<td><strong>{{$transaction->transaction_number}}</strong></td>
							</tr>
							<tr>
								<td>Mode of Payment:</td>
								<td> {{ $transaction->payment_mode->name }} </td>
							</tr>
							<tr>
								<td>Status</td>
								<td>{{$transaction->status->name}}</td>
							</tr>
							<tr>
								<td>Date</td>
								<td>{{$transaction->created_at->format('F d, Y')}}</td>
							</tr>

						</tbody>





					</table>
					{{-- end of table --}}
					<hr>
					<table class="table table-borderless">
						<thead>
							<th scope="col">Product Name</th>
							<th scope="col">Quantity</th>
							<th scope="col">Unit Price</th>
							<th scope="col" class="text-center">Amount</th>
						</thead>
						<tbody>
							@foreach ($transaction->products as $transaction_product)
							<tr>

								<td>{{$transaction_product->name }}</td>
								<td>{{$transaction_product->pivot->quantity }}</td>
								<td>&#8369; 
									<span>
										{{ number_format($transaction_product->pivot->price) }}
									</span>
								</td>
								<td class="text-center">&#8369; 
									<span>
										{{ number_format($transaction_product->pivot->subtotal) }}
									</span>
								</td>

							</tr>
							@endforeach
						</tbody>
						<tfoot>
							<tr>
								<th scope="row" colspan="3" class="text-right">Total</th>
								<td scope="row" colspan="3" class="text-center">&#8369; 
									<span>
										{{ number_format($transaction->total) }}
								</span></td>
							</tr>

							
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>

@endsection