routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', function () {
    return redirect(route('products.index'));
});


Route::get('/home', 'ProductController@index');

// Route::get('/cart', function() {
// 	return view('cart');
// })->name('cart');

Route::post('transaction/paypal/create', 'TransactionController@paypal_store');

Route::delete('/carts/clear', 'CartController@clearCart')->name('carts.clear');

Route::resource('products', 'ProductController');

Route::resource('categories', 'CategoryController');

Route::resource('carts', 'CartController');

Route::resource('transactions', 'TransactionController');

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Transaction;
use Session;


class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Transaction $transaction )
    {
        //Admin should not be able to access this

        // flow
        // if there is session cart:
        // get the ids of each product from our session and put them in an array
        // for each product, add quantity and subtotal as an attribute
        // compute total
        // if the is no session cart, send a message saying "No items in cart"


        // products
            // name
            // price
            // quantity
            // subtotal
        // total


        
        $products = [];
        $total = 0;

        if (Session::has('cart')) {
            # code...
            // get all keys of session
            $product_ids = array_keys(Session::get('cart'));

            // we use the ids to query to the database and select only needed products
            $products = Product::find($product_ids);
            // dd($products);

            foreach ($products as $product) {

                // add the product quantity as an attribute
                $product['quantity'] = Session::get("cart.$product->id");
                $product['subtotal'] = $product['price'] * $product['quantity'];

                $total += $product['subtotal'];

            }

            return view('carts.index')->with('products', $products)->with('total', $total);

        }

        return view('carts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Transaction $transaction)
    {
        
        $request->validate([
            'id' => 'required',
            'quantity' => 'required|numeric|min:1|max:99'
        ]);

        // we want our cart session to look like this format
        // $cart = [
        //     id=>quantity
        //     id=>quantity
        //     id=>quantity
        // ]

        // get the request input
        //
        $product_quantity = $request->input('quantity');
        $id = $request->input('id');

        // set entry to be pass to session
        $add_to_cart = [
            $id => $product_quantity
        ];

        // store to session
        // $request->session()->put("cart", [$add_to_cart]);
        $request->session()->put("cart.$id", $product_quantity);
        return redirect(route('carts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        // dd($request->input());
       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Session::forget("cart.$id");

        return redirect(route('carts.index'));
    }

    public function clearCart()
    {
        Session::forget("cart");
        return redirect(route('carts.index'));
    }
}

resources/views/carts/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h3 class="text-center">
					My Cart Details
				</h3>
			</div>
		</div>

		<div class="row">
			<div class="col-12 col-md-10 mx-auto">
				{{-- if the count of session cart is more than zero and session have a cart session --}}
				@if (Session::has('cart') && count(Session::get('cart')))
					<div class="table-responsive">
						 <table class="table table-striped table-hover text-center">
							<thead>
								<tr>
									<th>Name</th>
									<th>Unit Price</th>
									<th>Quantity</th>
									<th>Subtotal</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								{{-- {{dd(Session::get('cart'))}} --}}
								{{-- {{ dd($products) }}	 --}}
								@foreach ($products as $product)	
									<tr>
										<th scope="row">{{ $product->name }}</th>
										<td>&#8369; <span class="product-price">{{ $product->price }}</span></td>
										<td>
											<form action="{{ route('carts.store', ['id' ,$product->id]) }}" method="POST" class="add-to-cart-field">
												@csrf
												<input type="hidden" name="id" value="{{ $product->id }} ">
												<div class="form-group">
													<div class="input-group">
														<input type="text" class="form-control input-quantity" min="1" name="quantity" data-id="{{ $product->id }}" value="{{ $product->quantity }}" >
														<div class="input-group-append" id="button-addon4">
															<button class="btn btn-outline-success deduct-quantity" type="button" data-id="{{ $product->id }}">-</button>
															<button class="btn btn-outline-success add-quantity" type="button" data-id="{{ $product->id }}">+</button>
														</div>
													</div>
												</div>
												<button class="btn btn-success btn-block">Update Quantity</button>
												{{-- <a type="submit" href="" class="btn btn-success btn-block my-1">
													Update Quantity
												</a> --}}
											</form>
										</td>
										<td>
											&#8369; <span class="product-subtotal">{{ $product->subtotal }}</span>
										</td>
										<td>
											<form method="POST" action="{{ route('carts.destroy', ['cart' => $product->id]) }}">
												@csrf
												@method('DELETE')
												<button class="btn btn-danger btn-block">Remove from cart</button>
											</form>
										</td>
									</tr>
								@endforeach
								
							</tbody>
							<tfoot>
								<tr>
									<td  colspan="3" class="text-right"  >Total</td>
									<td> &#8369; <span class="total_price">{{ $total }}</span></td>
									<td>
										@if(Auth::user())
										<form method="post" action="{{ route('transactions.store') }}" >
											@csrf
											<button class="btn btn-primary btn-block">Checkout Cart</button>
										</form>

										@else
											{{-- <a href="{{ route('login') }}" class="btn btn-primary btn-block">Checkout Cart</a> --}}
											<button class="btn btn-primary btn-block" data-toggle="modal" data-target="#auth-modal" >Checkout Cart</button>
										@endif

										@guest

										@else
										<hr>
										<p class="mb-0"><small>Pay via:</small></p>
										<div class="py-3" id="paypal-button-container"></div>
										@endguest

									</td>
								</tr>

							</tfoot>		 	
						 </table>
					</div>

				<form action="{{ route('carts.clear') }}" method="POST">
					@csrf
					@method('DELETE')
					<button class="btn btn-danger w-100 ">Empty cart</button>
				</form>

				@else
					@if(Session::has('Checkout_success'))
						<div class="alert alert-success text-center ">
							{{ Session::get('Checkout_success') }}
						</div>
					@else
					
					<div class="text-center alert alert-warning">
						<h5>No items in cart. </h5>
						<small><a href="{{ route('products.index') }}">Go to Products</a></small>
					</div>
					@endif
				@endif
			</div>
		</div>
	</div>


	{{-- MODAL --}}
	<div class="modal fade" id="auth-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Login</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="card-body">
                    <form method="POST" action="{{ route('login') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                                    <label class="form-check-label" for="remember">
                                        {{ __('Remember Me') }}
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Login') }}
                                </button>

                                @if (Route::has('password.request'))
                                    <a class="btn btn-link" href="{{ route('password.request') }}">
                                        {{ __('Forgot Your Password?') }}
                                    </a>
                                @endif
                            </div>
                        </div>
                    </form>
                </div>

			</div>
		</div>
	</div>


	@if(Session::has('cart') && count(Session::get('cart')))
	<script 
		src="https://www.paypal.com/sdk/js?client-id=AXjMwT4BNblmJ1gZFvkoNI_kd8fQD6bMtEd4WqZDfK0Hb3v9PtF8QeqG97b7stuvZPjWighBJiCEyk7E">
	</script>

	<script>
		paypal.Buttons({
	    createOrder: function(data, actions) {
	      // Set up the transaction
	      return actions.order.create({
	        purchase_units: [{
	          amount: {
	            value: '{{ $total }}'
	            //you can also use document.querySelector('#total_price').innerHTML
	          }
	        }]
	      });
	    },
	    onApprove: function(data, actions) {
			return actions.order.capture().then(function(details) {
				// console.log(details.id);


				fetch('http://localhost:8001/transaction/paypal/create', {
					method : 'post',
					body : JSON.stringify({ 
						transactionNumber: details.id
					}),
					headers : {
						'X-CSRF-TOKEN' : document.querySelector('meta[name="csrf-token"]').getAttribute('content'),
						'Accept' : "application/json"
					}
				})
				.then( response => response.json())
				.then( result => {
					window.location = result.url
					// console.log(result.url);
				});


				// alert('Transaction completed by ' + details.payer.name.given_name);
				// // Call your server to save the transaction
				// return fetch('/paypal-transaction-complete', {
				// 	method: 'post',
				// 	headers: {
				// 		'content-type': 'application/json'
				// 	},
				// 	body: JSON.stringify({
				// 		orderID: data.orderID
				// 	})
				// });
			});
	    }
	  }).render('#paypal-button-container');

	   
	</script>
	@endif
@endsection