routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', function () {
    return redirect(route('products.index'));
});


Route::get('/home', 'ProductController@index');

// Route::get('/cart', function() {
// 	return view('cart');
// })->name('cart');

Route::post('transaction/paypal/create', 'TransactionController@paypal_store');

Route::delete('/carts/clear', 'CartController@clearCart')->name('carts.clear');

Route::resource('products', 'ProductController');

Route::resource('categories', 'CategoryController');

Route::resource('carts', 'CartController');

Route::resource('transactions', 'TransactionController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    //
    use SoftDeletes;
    public function category(){
    	return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Str;
// this will get all the category on the database to pass it to create form
use App\Category;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('products.index')->with('products', $products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Product $product)
    {
        $this->authorize('create', $product);

        $categories = Category::all();
        return view('products.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Product $product)
    {

        $this->authorize('create', $product);

        // FLOW
        // 1. validate each field (validation errors will display in views)
        // 2. save uploaded image (because we need the path. To get the the path which will be saved to the database.)
        // 3. get input values from the form
        // 4. save the details to the database
        // 5. redirect to a single product redirect(show)

        // 1
        $request->validate([
            'name' => 'required|string',
            'price' => 'required|numeric',
            'category' => 'required',
            'image' => 'required|image|max:30000',
            'description' => 'required|string'
        ]);

        // 2.1 get uploaded file

        // 2.2 get uploaded filename

        // 2.3 get uploaded file extension name

        // 2.4 generate new name with random characters

        // 2.5 save the new file to public folder

        // 2.1
        $file = $request->file('image');

        // 2.2
        $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        
        // 2.3
        $file_extension = $file->extension();

        // 2.4
        $random_chars = Str::random(10);

        $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." . $file_extension;

        // dd($new_file_name);

        // 2.5
        $file_path = $file->storeAs('images', $new_file_name, 'public');


        // 3. get input values from form
        // $data = $request->all(
        //     'name',
        //     'price',
        //     'category',
        //     'description'
        // );
        
        $name = $request->input('name');
        $price = $request->input('price');
        $category_id = $request->input('category');
        $description = $request->input('description');
        $image = $file_path;

        // 4. save details to database
        $product = new Product;
        $product->name = $name;
        $product->price = $price;
        $product->category_id = $category_id;
        $product->description = $description;
        $product->image = $image;
        $product->save();

        // 5. redirect
        return redirect(route( 'products.show', ['product' => $product->id] ));


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show')->with('product', $product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $this->authorize('update', $product);

        $categories = Category::all();
        return view('products.edit')->with('product', $product)->with('categories', $categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        // FLOW
        // 1. check if all fields are not empty except image
        // 2. Update database if there are differences between the details from input form and the current details of the product

        $this->authorize('update', $product);
        // 1.
        $request->validate([
            'name' => 'required|string',
            'price' => 'required|numeric',
            'category' => 'required',
            // 'image' => 'required|image|max:30000',
            'description' => 'required|string'
        ]);

        // 2.
        

        if ( 
            !$request->hasFile('image') &&
            $product->name == $request->input('name') &&
            $product->price == $request->input('price') &&
            $product->category_id == $request->input('category') &&
            $product->description == $request->input('description')
        ) {
            $request->session()->flash('update_failed','There are no changes made.');
            
        }
        else {
            // update the entry in the database and return the updated entry

            // check if there is a file uploaded
            if($request->hasFile('image')){
                $request->validate([
                    'image' => 'required|image|max:30000'
                ]);

                $file = $request->file('image');
                $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $file_extension = $file->extension();
                $random_chars = Str::random(10);
                $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." . $file_extension;
                $file_path = $file->storeAs('images', $new_file_name, 'public');
                $product->image = $file_path;
            }

            // set the new image path as image value of product
            $product->name = $request->input('name');
            $product->price = $request->input('price');
            $product->category_id = $request->input('category');
            $product->description = $request->input('description');
            // dd($product);
            $product->save();

            $request->session()->flash('update_success', 'Product successfully updated');

        }
        return redirect(route('products.edit', ['product' => $product->id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Product $product)
    {
        $this->authorize('delete', $product);
        $product->delete();
        // $request->session()->flash('destroy_success', 'Product deleted');
        return redirect(route('products.index'))->with('destroy_success', 'Product Deleted.');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')


@section('content')

	<div class="container-fluid">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">
					Edit Product
				</h3>
				<hr>
				<form action="{{ route('products.store') }} " method="POST" enctype="multipart/form-data" >
					@csrf

					
					{{-- Input for name --}}
					<div class="form-group">
						<label for="name">Product Name:</label>
						<input type="text" name="name" id="name" class="form-control">

						@if ($errors->has('name'))
							<div class="alert alert-danger">
								<small class="mb-0">Product name is required.</small>
							</div>
						@endif
					</div>

					{{-- Input for price --}}
					<div class="form-group">
						<label for="price">Product Price:</label>
						<input type="number" name="price" id="price" class="form-control" min="1">
						@if ($errors->has('price'))
							<div class="alert alert-danger">
								<small class="mb-0">Product price is required.</small>
							</div>
						@endif
					</div>

					{{-- Input for category --}}
					<div class="form-group">
						<label for="category">Product Category:</label>
						<select class="form-control" id="category" name="category">

							@foreach ($categories as $category)
								<option value="{{ $category->id }}">{{ $category->name }}</option>
							@endforeach
							
					    </select>
					</div>


					{{-- Input for image --}}
					<div class="form-group">
						<label for="image">Product Image:</label>
						<input type="file" name="image" id="image" class="form-control-file">
						@if ($errors->has('image'))
							{{-- {{dd($errors)}} --}}
							<div class="alert alert-danger">
								<small class="mb-0">Product image is required. Check if image is not greater than 3mb.</small>
							</div>
						@endif
					</div>

					{{-- Input for description --}}
					<div class="form-group">
						<label for="description">Product Description:</label>
						<textarea 
							name="description" 
							id="description" 
							class="form-control" 
							min="1" 
							cols="30" 
							rows="10"
						></textarea>
						@if ($errors->has('description'))
							<div class="alert alert-danger">
								<small class="mb-0">Product description is required.</small>
							</div>
						@endif
					</div>

					<button class="btn btn-dark btn-block">Add Item</button>

				</form>
			</div>
			<div class="col-12 col-md-2 mx-auto">
				<form action="{{ route('categories.store') }}" method="POST">
					@csrf
					@if (Session::has('category_message'))
						<div class="alert- alert-success">
							<small>
								{{ Session::get('category_message') }}
							</small>
						</div>
					@endif

					@if ($errors->has('add-category'))
						<div class="alert alert-danger">
							<small>
								Category not added.
							</small>
						</div>
					@endif

					<div class="form-group">
						<label for="add-category">Add category: </label>
						<input type="text" name="add-category" id="add-category" class="form-control">
					</div>
					<button class="btn btn-block btn-success">Add Category</button>

				</form>
			</div>

		</div>
	</div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')


@section('content')


	<div class="container-fluid">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">
					Add Product
				</h3>
				<hr>
				@if(Session::has('update_failed'))
					<div class="alert alert-warning">
						{{ Session::get('update_failed') }}
					</div>
				@endif

				@if (Session::has('update_success'))
					<div class="alert alert-success">
						{{ Session::get('update_success') }}
					</div>
				@endif
				<form action="{{ route('products.update', ['product' => $product->id]) }}" method="POST" enctype="multipart/form-data" >
					
					@csrf
					@method('PUT')

					<div class="form-group">
						<label for="name">Product Name:</label>
						<input type="text" name="name" id="name" class="form-control" value="{{$product->name}}">

						@if ($errors->has('name'))
							<div class="alert alert-danger">
								<small class="mb-0">Product name is required.</small>
							</div>
						@endif
					</div>

					{{-- Input for price --}}
					<div class="form-group">
						<label for="price">Product Price:</label>
						<input  type="number" name="price" id="price" class="form-control" min="1" value="{{$product->price}}">
						@if ($errors->has('price'))
							<div class="alert alert-danger">
								<small class="mb-0">Product price is required.</small>
							</div>
						@endif
					</div>

					{{-- Input for category --}}
					<div class="form-group">
						<label for="category">Product Category:</label>
						<select class="form-control" id="category" name="category">

							@foreach ($categories as $category)
								<option 
									value="{{ $category->id }}"
									@if ($product->category_id == $category->id)
										selected 
									@endif
								>
									{{ $category->name }}
								</option>
							@endforeach
							
					    </select>
					</div>


					{{-- Input for image --}}
					<div class="form-group">
						<label for="image">Product Image:</label>
						<input type="file" name="image" id="image" class="form-control-file" > 
						@if ($errors->has('image'))
							{{-- {{dd($errors)}} --}}
							<div class="alert alert-danger">
								<small class="mb-0">Product image is required. Check if image is not greater than 3mb.</small>
							</div>
						@endif
					</div>

					{{-- Input for description --}}
					<div class="form-group">
						<label for="description">Product Description:</label>
						<textarea 
							name="description" 
							id="description" 
							class="form-control" 
							min="1" 
							cols="30" 
							rows="10"
						>{{ $product->description}}</textarea>


						@if ($errors->has('description'))
							<div class="alert alert-danger">
								<small class="mb-0">Product description is required.</small>
							</div>
						@endif
					</div>

					<button class="btn btn-warning btn-block">Update</button>

				</form>

			</div>
		</div>
	</div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container">
		<div class="row">
			<div class="col-12 ">
				<div class="jumbotron text-center header">
					<h1>
						<i class="fab fa-empire"></i> MJSA Military Supply Co. <i class="fab fa-empire"></i>
					</h1>
				</div>
			</div>
		</div>
		@if (Session::has('destroy_success'))
			<div class="row">
				<div class="col-12">
					<div class="alert alert-success">
						{{ Session::get('destroy_success') }}
					</div>
				</div>
			</div>
		@endif

		<div class="row">
			<div class="col-12 col-md-10 mx-auto">
				<div class="row">
					@foreach ($products as $product)
						<div class="col-12 col-md-4">
							<div class="card shadow p-3 mb-5 bg-white rounded">
								<img 
								src="{{ url('/public/' . $product->image )  }}" 
								class="card-img-top"
								>
								<h5 class="card-title">
									{{ $product->name }}
								</h5>
								<p class="card-subtitle">
									<strong>
										&#8369; {{ $product->price }}
									</strong>
								</p>
								<p> {{ $product->category->name }} </p>



								<div class="card-footer">

									@cannot('isAdmin')
									<form action="{{ route('carts.store') }}" method="POST" class="add-to-cart-field">
										@csrf
										<input type="hidden" name="id" value="{{ $product->id }} ">

										<div class="form-group">
											<label for="quantity"><small>Quantity: </small></label>
											<div class="input-group">
												<input type="text" class="form-control input-quantity" value="1" min="1" name="quantity" data-id="{{ $product->id }}" >
												<div class="input-group-append" id="button-addon4">
													<button class="btn btn-outline-success deduct-quantity" type="button" data-id="{{ $product->id }}">-</button>
													<button class="btn btn-outline-success add-quantity" type="button" data-id="{{ $product->id }}">+</button>
												</div>
											</div>
										</div>
										<button class="btn btn-success btn-block my-1"><i class="fas fa-cart-plus"></i> Add To Cart</button>
										{{-- <a type="submit" class="btn btn-success btn-block my-1">
											Add To Cart
										</a> --}}
									</form>
									@endcannot

									<a 
									href="{{ route('products.show', ['product' => $product->id])}}" 
									class="btn btn-secondary btn-block my-1">View Product
									</a>
									
									@can('isAdmin')
									<a 
									href="{{ route('products.edit', ['product' => $product->id]) }} " 
									class="btn btn-block btn-warning my-1">Edit Product
									</a>


									<form action="{{ route('carts.destroy', ['product' => $product->id]) }}" method="POST">
										@csrf
										@method('DELETE')
										<button class="btn btn-danger btn-block my-1">Delete Product</button>
									</form>
									@endcan

								</div>
							</div>
						</div>
					@endforeach
				</div>


			</div>
		</div>
	</div>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')

	{{-- {{ dd($product) }} --}}
	<div class="container-fluid">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">
					View Product
				</h3>
				<hr>
				<div class="card shadow p-3 mb-5 bg-white rounded ">
					<img 
					src="{{ url('/public/' . $product->image )  }}" 
					class="card-img-top"
					>

					<div class="card-body">

						<h2 class="card-title">
							{{ $product->name }}
						</h2>
						<p class="card-subtitle">
							<strong>
								&#8369; {{ $product->price }}
							</strong>
						</p>
						<p class="card-text">
							{{ $product->description }}
						</p>
					</div>

					<div class="card-footer">

						@cannot('isAdmin')
						<form action="{{ route('carts.store') }}" method="POST" class="add-to-cart-field">
							@csrf
							<input type="hidden" name="id" value="{{ $product->id }} ">

							<div class="form-group">
								<label for="quantity"><small>Quantity: </small></label>
								<div class="input-group">
									<input type="text" class="form-control input-quantity" value="1" min="1" name="quantity" data-id="{{ $product->id }}" >
									<div class="input-group-append" id="button-addon4">
										<button class="btn btn-outline-success deduct-quantity" type="button" data-id="{{ $product->id }}">-</button>
										<button class="btn btn-outline-success add-quantity" type="button" data-id="{{ $product->id }}">+</button>
									</div>
								</div>
							</div>
							<button class="btn btn-success btn-block my-1">Add To Cart</button>
							{{-- <a type="submit" class="btn btn-success btn-block my-1">
								Add To Cart
							</a> --}}
						</form>

						@endcannot

						<a 
						href="{{ route('products.show', ['product' => $product->id])}}" 
						class="btn btn-secondary btn-block my-1">View Product
						</a>
						
						@can('isAdmin')
						<a 
						href="{{ route('products.edit', ['product' => $product->id]) }} " 
						class="btn btn-block btn-warning my-1">Edit Product
						</a>


						<form action="{{ route('products.destroy', ['product' => $product->id ])}} " method="POST">
							@csrf
							@method('DELETE')
							<button class="btn btn-danger btn-block my-1">Delete Product</button>
						</form>
						@endcan

					</div>
				</div>
			</div>
		</div>
	</div>

@endsection